### ISSUE TITLE
Running myth results in TemplateNotFound: report_as_text.jinja2 error

### ISSUE THREAD

**Issue by astudnev** [ConsenSys/mythril#241]
**Describe the bug**

**To Reproduce**
1. install myth using instructions from https://github.com/ConsenSys/mythril/wiki/Install-from-Pypi-on-Mac-OS
2. run command myth -x smartcontract.sol
3. See error

**Expected behavior**
Test to run on smart contract

**Screenshots**

myth -x build/src/NYNJACoin.sol 
Traceback (most recent call last):
  File "/anaconda3/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/anaconda3/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 205, in main
    'text': report.as_text(),
  File "/anaconda3/lib/python3.6/site-packages/mythril/analysis/report.py", line 55, in as_text
    template = Report.environment.get_template('report_as_text.jinja2')
  File "/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/anaconda3/lib/python3.6/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/anaconda3/lib/python3.6/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/anaconda3/lib/python3.6/site-packages/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: report_as_text.jinja2

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by astudnev** [comment]
Looks like the distribution pip3 install missing 2 files:

mythril/analysis/templates/report_as_text.jinja2

mythril/analysis/templates/report_as_markdown.jinja2

**Comment by alexaltair** [comment]
I got the same error, pushing the following CircleCI config;
```
version: 2
jobs:
  mythril:
    docker:
      - image: ubuntu:bionic
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -y software-properties-common
      - run: add-apt-repository -y ppa:ethereum/ethereum
      - run: apt-get update
      - run: apt-get install -y solc libssl-dev python3-pip=9.0.1-2 python3-dev pandoc
      - run: ln -s /usr/bin/python3 /usr/local/bin/python
      - run: pip3 install mythril
      - run: myth -x ./contracts/MyContract.sol
workflows:
  version: 2
  test_all:
    jobs:
      - mythril
```
