### ISSUE TITLE
Sonarcloud code coverage

### ISSUE THREAD

**Issue by JoranHonig** [ConsenSys/mythril#457]
## Description

Sonarcloud supports displaying coverage information, it would be usefull if we could put the coverage results of our testsuite over there

**Comment by JoranHonig** [comment]
@norhh This doesn't seem to be fixed yet, is that right?

**Comment by norhh** [comment]
Yep, it requires some weird xml format, I just gave it a shot with typical xml format

**Comment by norhh** [comment]
@JoranHonig , by any chance can add to circleci to run the coverage_report.sh? as my local circleci is throwing some permission denied errors out of nowhere suddenly and I don't want to spam the gihub's circleci.

**Comment by JoranHonig** [comment]
I'm not 100% sure what I should do here

Do you wan't me to add something like the following to the config.yaml and run circleci locally?
```
      - run:
          name: coverage
          command: ./coverage_report.sh
          working_directory: /home/mythril
```
